#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MinionLib.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class BinarySerializationGenerator : IIncrementalGenerator
{
    private const string GeneratedSerializableMetadataName = "MinionLib.Component.Interfaces.IGeneratedBinarySerializable";
    private const string ComponentStateAttributeMetadataName = "MinionLib.Component.Core.ComponentStateAttribute";
    private const string ComponentStateGenericAttributeMetadataName = "MinionLib.Component.Core.ComponentStateAttribute`1";
    private const string NoGeneratedSerializationMetadataName = "MinionLib.Component.Core.NoGeneratedSerializationAttribute";
    private const string CardComponentMetadataName = "MinionLib.Component.CardComponent";

    private static readonly DiagnosticDescriptor ImplementationMustBeClass = new(
        id: "MLSG100",
        title: "IGeneratedBinarySerializable implementation must be a class",
        messageFormat: "Type '{0}' implements IGeneratedBinarySerializable but is not a class",
        category: "MinionLib.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingParameterlessCtor = new(
        id: "MLSG101",
        title: "Missing parameterless constructor",
        messageFormat: "Type '{0}' implements IGeneratedBinarySerializable and must define a parameterless constructor",
        category: "MinionLib.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor TypeMustBePartialForGeneration = new(
        id: "MLSG102",
        title: "Type must be partial for generated serialization",
        messageFormat: "Type '{0}' is eligible for generated serialization but is not declared partial; generation skipped",
        category: "MinionLib.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => { Emit(spc, compilation); });
    }

    private static void Emit(SourceProductionContext context, Compilation compilation)
    {
        var serializableSymbol = compilation.GetTypeByMetadataName(GeneratedSerializableMetadataName);
        if (serializableSymbol == null)
            return;

        var componentStateAttribute = compilation.GetTypeByMetadataName(ComponentStateAttributeMetadataName);
        var componentStateGenericAttribute = compilation.GetTypeByMetadataName(ComponentStateGenericAttributeMetadataName);
        var noGeneratedAttribute = compilation.GetTypeByMetadataName(NoGeneratedSerializationMetadataName);
        var cardComponentType = compilation.GetTypeByMetadataName(CardComponentMetadataName);

        foreach (var type in GetAllTypes(compilation.Assembly.GlobalNamespace))
        {
            if (!Implements(type, serializableSymbol) || type.TypeKind == TypeKind.Interface)
                continue;

            if (type.TypeKind != TypeKind.Class)
            {
                context.ReportDiagnostic(Diagnostic.Create(ImplementationMustBeClass,
                    type.Locations.FirstOrDefault(), type.ToDisplayString()));
                continue;
            }

            if (!HasParameterlessConstructor(type))
                context.ReportDiagnostic(Diagnostic.Create(MissingParameterlessCtor,
                    type.Locations.FirstOrDefault(), type.ToDisplayString()));

            if (HasAttribute(type, noGeneratedAttribute) || HasExplicitSerializationMethods(type))
                continue;

            var props = GetStateProperties(type, componentStateAttribute, componentStateGenericAttribute);
            if (props.Length == 0)
                continue;

            if (!IsPartial(type))
            {
                context.ReportDiagnostic(Diagnostic.Create(TypeMustBePartialForGeneration,
                    type.Locations.FirstOrDefault(), type.ToDisplayString()));
                continue;
            }

            var source = BuildSource(type, props, cardComponentType != null && InheritsFrom(type, cardComponentType),
                serializableSymbol);
            context.AddSource(BuildHintName(type), SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(INamedTypeSymbol type, ImmutableArray<IPropertySymbol> props, bool isCardComponentDerived,
        INamedTypeSymbol serializableSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            sb.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
            sb.AppendLine();
        }

        AppendContainingTypeDeclarations(sb, type);

        var methodPrefix = isCardComponentDerived ? "public override" : "public";
        var uniqueId = 0;

        sb.Append("    ").Append(methodPrefix)
            .AppendLine(" void Serialize(global::System.Buffers.ArrayBufferWriter<byte> writer)");
        sb.AppendLine("    {");
        if (isCardComponentDerived)
            sb.AppendLine("        base.Serialize(writer);");
        foreach (var prop in props)
            EmitSerializeForType(sb, prop.Type, $"this.{prop.Name}", 2, ref uniqueId, serializableSymbol);
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.Append("    ").Append(methodPrefix)
            .AppendLine(" bool Deserialize(ref global::System.ReadOnlySpan<byte> reader)");
        sb.AppendLine("    {");
        if (isCardComponentDerived)
            sb.AppendLine("        if (!base.Deserialize(ref reader)) return false;");
        foreach (var prop in props)
            EmitDeserializeForType(sb, prop.Type, $"this.{prop.Name}", 2, ref uniqueId, serializableSymbol);

        sb.AppendLine("        return true;");
        sb.AppendLine("    }");

        AppendContainingTypeClosures(sb, type);
        return sb.ToString();
    }

    private static void EmitSerializeForType(StringBuilder sb, ITypeSymbol type, string expr, int indent, ref int id,
        INamedTypeSymbol serializableSymbol)
    {
        var p = Indent(indent);

        if (type.NullableAnnotation == NullableAnnotation.Annotated && type is not INamedTypeSymbol { SpecialType: SpecialType.System_String })
        {
            var has = $"__has_{id++}";
            sb.Append(p).Append("var ").Append(has).Append(" = ").Append(expr).AppendLine(" != null;");
            sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteBoolean(writer, ").Append(has).AppendLine(");");
            sb.Append(p).Append("if (").Append(has).AppendLine(")");
            sb.Append(p).AppendLine("{");
            EmitSerializeForType(sb, RemoveNullable(type), expr + "!", indent + 1, ref id, serializableSymbol);
            sb.Append(p).AppendLine("}");
            return;
        }

        if (type is IArrayTypeSymbol array && array.Rank == 1)
        {
            var len = $"__len_{id++}";
            var i = $"__i_{id++}";
            sb.Append(p).Append("if (").Append(expr).AppendLine(" == null)");
            sb.Append(p).AppendLine("{");
            sb.Append(p).AppendLine("    global::MinionLib.Component.Core.SerializationUtils.WriteInt32(writer, -1);");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            sb.Append(p).Append("    var ").Append(len).Append(" = ").Append(expr).AppendLine("!.Length;");
            sb.Append(p).Append("    global::MinionLib.Component.Core.SerializationUtils.WriteInt32(writer, ").Append(len).AppendLine(");");
            sb.Append(p).Append("    for (var ").Append(i).Append(" = 0; ").Append(i).Append(" < ").Append(len).Append("; ").Append(i)
                .AppendLine("++)");
            sb.Append(p).AppendLine("    {");
            EmitSerializeForType(sb, array.ElementType, expr + "![" + i + "]", indent + 2, ref id, serializableSymbol);
            sb.Append(p).AppendLine("    }");
            sb.Append(p).AppendLine("}");
            return;
        }

        if (TryGetListElementType(type, out var listElement))
        {
            var len = $"__len_{id++}";
            var i = $"__i_{id++}";
            sb.Append(p).Append("if (").Append(expr).AppendLine(" == null)");
            sb.Append(p).AppendLine("{");
            sb.Append(p).AppendLine("    global::MinionLib.Component.Core.SerializationUtils.WriteInt32(writer, -1);");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            sb.Append(p).Append("    var ").Append(len).Append(" = ").Append(expr).AppendLine("!.Count;");
            sb.Append(p).Append("    global::MinionLib.Component.Core.SerializationUtils.WriteInt32(writer, ").Append(len).AppendLine(");");
            sb.Append(p).Append("    for (var ").Append(i).Append(" = 0; ").Append(i).Append(" < ").Append(len).Append("; ").Append(i)
                .AppendLine("++)");
            sb.Append(p).AppendLine("    {");
            EmitSerializeForType(sb, listElement!, expr + "![" + i + "]", indent + 2, ref id, serializableSymbol);
            sb.Append(p).AppendLine("    }");
            sb.Append(p).AppendLine("}");
            return;
        }

        if (type.SpecialType == SpecialType.System_String)
        {
            sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteString(writer, ").Append(expr).AppendLine(");");
            return;
        }

        if (TryEmitPrimitiveSerialize(sb, type, expr, indent))
            return;

        if (type.TypeKind == TypeKind.Enum)
        {
            var underlying = ((INamedTypeSymbol)type).EnumUnderlyingType!;
            EmitSerializeForType(sb, underlying, "(" + underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")" + expr,
                indent, ref id, serializableSymbol);
            return;
        }

        if (ImplementsSerializable(type, serializableSymbol))
        {
            sb.Append(p).Append("if (").Append(expr).AppendLine(" == null)");
            sb.Append(p).AppendLine("{");
            sb.Append(p).AppendLine("    global::MinionLib.Component.Core.SerializationUtils.WriteBoolean(writer, false);");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            sb.Append(p).AppendLine("    global::MinionLib.Component.Core.SerializationUtils.WriteBoolean(writer, true);");
            sb.Append(p).Append("    global::MinionLib.Component.Core.SerializationUtils.WriteSerializableBlock(writer, ")
                .Append(expr).AppendLine("!);");
            sb.Append(p).AppendLine("}");
            return;
        }

        sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteJson<")
            .Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">(writer, ").Append(expr).AppendLine(");");
    }

    private static void EmitDeserializeForType(StringBuilder sb, ITypeSymbol type, string targetExpr, int indent, ref int id,
        INamedTypeSymbol serializableSymbol)
    {
        var p = Indent(indent);
        var canAssignNull = CanAssignNullOnDeserialize(type);

        if (type.NullableAnnotation == NullableAnnotation.Annotated && type is not INamedTypeSymbol { SpecialType: SpecialType.System_String })
        {
            var has = $"__has_{id++}";
            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadBoolean(ref reader, out var ")
                .Append(has).AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append("if (!").Append(has).AppendLine(")");
            sb.Append(p).AppendLine("{");
            sb.Append(p).Append(targetExpr).AppendLine(" = default;");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            EmitDeserializeForType(sb, RemoveNullable(type), targetExpr, indent + 1, ref id, serializableSymbol);
            sb.Append(p).AppendLine("}");
            return;
        }

        if (type is IArrayTypeSymbol array && array.Rank == 1)
        {
            var len = $"__len_{id++}";
            var arr = $"__arr_{id++}";
            var i = $"__i_{id++}";
            var item = $"__item_{id++}";
            var elementTypeName = array.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var arrayCreationExpr = BuildJaggedArrayCreationExpression(array, len);

            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadInt32(ref reader, out var ")
                .Append(len).AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append("if (").Append(len).AppendLine(" < -1)");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append("if (").Append(len).AppendLine(" == -1)");
            sb.Append(p).AppendLine("{");
            if (canAssignNull)
                sb.Append(p).Append("    ").Append(targetExpr).AppendLine(" = null;");
            else
                sb.Append(p).AppendLine("    return false;");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            sb.Append(p).Append("    var ").Append(arr).Append(" = ").Append(arrayCreationExpr).AppendLine(";");
            sb.Append(p).Append("    for (var ").Append(i).Append(" = 0; ").Append(i).Append(" < ").Append(len).Append("; ").Append(i)
                .AppendLine("++)");
            sb.Append(p).AppendLine("    {");
            sb.Append(p).Append("        ").Append(elementTypeName).Append(' ').Append(item)
                .Append(GetLocalInitializer(array.ElementType)).AppendLine();
            EmitDeserializeForType(sb, array.ElementType, item, indent + 2, ref id, serializableSymbol);
            sb.Append(p).Append("        ").Append(arr).Append("[").Append(i).Append("] = ").Append(item).AppendLine(";");
            sb.Append(p).AppendLine("    }");
            sb.Append(p).Append("    ").Append(targetExpr).Append(" = ").Append(arr).AppendLine(";");
            sb.Append(p).AppendLine("}");
            return;
        }

        if (TryGetListElementType(type, out var listElement))
        {
            var listTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var elemTypeName = listElement!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var len = $"__len_{id++}";
            var list = $"__list_{id++}";
            var i = $"__i_{id++}";
            var item = $"__item_{id++}";

            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadInt32(ref reader, out var ")
                .Append(len).AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append("if (").Append(len).AppendLine(" < -1)");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append("if (").Append(len).AppendLine(" == -1)");
            sb.Append(p).AppendLine("{");
            if (canAssignNull)
                sb.Append(p).Append("    ").Append(targetExpr).AppendLine(" = null;");
            else
                sb.Append(p).AppendLine("    return false;");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            sb.Append(p).Append("    var ").Append(list).Append(" = new ").Append(listTypeName).Append("(").Append(len).AppendLine(");");
            sb.Append(p).Append("    for (var ").Append(i).Append(" = 0; ").Append(i).Append(" < ").Append(len).Append("; ").Append(i)
                .AppendLine("++)");
            sb.Append(p).AppendLine("    {");
            sb.Append(p).Append("        ").Append(elemTypeName).Append(' ').Append(item)
                .Append(GetLocalInitializer(listElement!)).AppendLine();
            EmitDeserializeForType(sb, listElement!, item, indent + 2, ref id, serializableSymbol);
            sb.Append(p).Append("        ").Append(list).Append(".Add(").Append(item).AppendLine(");");
            sb.Append(p).AppendLine("    }");
            sb.Append(p).Append("    ").Append(targetExpr).Append(" = ").Append(list).AppendLine(";");
            sb.Append(p).AppendLine("}");
            return;
        }

        if (type.SpecialType == SpecialType.System_String)
        {
            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadString(ref reader, out var __str_")
                .Append(id).AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            var strVar = $"__str_{id++}";
            if (canAssignNull)
            {
                sb.Append(p).Append(targetExpr).Append(" = ").Append(strVar).AppendLine(";");
            }
            else
            {
                sb.Append(p).Append("if (").Append(strVar).AppendLine(" == null)");
                sb.Append(p).AppendLine("    return false;");
                sb.Append(p).Append(targetExpr).Append(" = ").Append(strVar).AppendLine("!;");
            }

            return;
        }

        if (TryEmitPrimitiveDeserialize(sb, type, targetExpr, indent, ref id))
            return;

        if (type.TypeKind == TypeKind.Enum)
        {
            var enumTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var underlying = ((INamedTypeSymbol)type).EnumUnderlyingType!;
            var underlyingTypeName = underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var raw = $"__enum_{id++}";

            sb.Append(p).Append(underlyingTypeName).Append(' ').Append(raw).AppendLine(" = default;");
            EmitDeserializeForType(sb, underlying, raw, indent, ref id, serializableSymbol);
            sb.Append(p).Append(targetExpr).Append(" = (").Append(enumTypeName).Append(")").Append(raw).AppendLine(";");
            return;
        }

        if (ImplementsSerializable(type, serializableSymbol))
        {
            var has = $"__has_{id++}";
            var obj = $"__obj_{id++}";
            var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadBoolean(ref reader, out var ")
                .Append(has).AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append("if (!").Append(has).AppendLine(")");
            sb.Append(p).AppendLine("{");
            if (canAssignNull)
                sb.Append(p).Append("    ").Append(targetExpr).AppendLine(" = null;");
            else
                sb.Append(p).AppendLine("    return false;");
            sb.Append(p).AppendLine("}");
            sb.Append(p).AppendLine("else");
            sb.Append(p).AppendLine("{");
            sb.Append(p).Append("    var ").Append(obj).Append(" = new ").Append(typeName).AppendLine("();");
            sb.Append(p).Append("    if (!global::MinionLib.Component.Core.SerializationUtils.TryReadSerializableBlock(ref reader, ")
                .Append(obj).AppendLine("))");
            sb.Append(p).AppendLine("        return false;");
            sb.Append(p).Append("    ").Append(targetExpr).Append(" = ").Append(obj).AppendLine(";");
            sb.Append(p).AppendLine("}");
            return;
        }

        var t = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadJson<").Append(t)
            .Append(">(ref reader, out var __json_").Append(id).AppendLine("))");
        sb.Append(p).AppendLine("    return false;");
        sb.Append(p).Append(targetExpr).Append(" = __json_").Append(id++).AppendLine(";");
    }

    private static bool TryEmitPrimitiveSerialize(StringBuilder sb, ITypeSymbol type, string expr, int indent)
    {
        var p = Indent(indent);
        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteBoolean(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_Byte:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteByte(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_SByte:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteByte(writer, unchecked((byte)").Append(expr)
                    .AppendLine("));");
                return true;
            case SpecialType.System_Int16:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteInt16(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_UInt16:
            case SpecialType.System_Char:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteUInt16(writer, (ushort)").Append(expr)
                    .AppendLine(");");
                return true;
            case SpecialType.System_Int32:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteInt32(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_UInt32:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteUInt32(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_Int64:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteInt64(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_UInt64:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteUInt64(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_Single:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteSingle(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_Double:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteDouble(writer, ").Append(expr).AppendLine(");");
                return true;
            case SpecialType.System_Decimal:
                sb.Append(p).Append("global::MinionLib.Component.Core.SerializationUtils.WriteDecimal(writer, ").Append(expr).AppendLine(");");
                return true;
            default:
                return false;
        }
    }

    private static bool TryEmitPrimitiveDeserialize(StringBuilder sb, ITypeSymbol type, string targetExpr, int indent, ref int id)
    {
        var p = Indent(indent);
        var temp = $"__v_{id++}";
        string? readCall = type.SpecialType switch
        {
            SpecialType.System_Boolean => "TryReadBoolean",
            SpecialType.System_Byte => "TryReadByte",
            SpecialType.System_Int16 => "TryReadInt16",
            SpecialType.System_UInt16 => "TryReadUInt16",
            SpecialType.System_Int32 => "TryReadInt32",
            SpecialType.System_UInt32 => "TryReadUInt32",
            SpecialType.System_Int64 => "TryReadInt64",
            SpecialType.System_UInt64 => "TryReadUInt64",
            SpecialType.System_Single => "TryReadSingle",
            SpecialType.System_Double => "TryReadDouble",
            SpecialType.System_Decimal => "TryReadDecimal",
            _ => null
        };

        if (type.SpecialType == SpecialType.System_SByte)
        {
            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadByte(ref reader, out var ").Append(temp)
                .AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append(targetExpr).Append(" = unchecked((sbyte)").Append(temp).AppendLine(");");
            return true;
        }

        if (type.SpecialType == SpecialType.System_Char)
        {
            sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.TryReadUInt16(ref reader, out var ").Append(temp)
                .AppendLine("))");
            sb.Append(p).AppendLine("    return false;");
            sb.Append(p).Append(targetExpr).Append(" = (char)").Append(temp).AppendLine(";");
            return true;
        }

        if (readCall == null)
            return false;

        sb.Append(p).Append("if (!global::MinionLib.Component.Core.SerializationUtils.").Append(readCall)
            .Append("(ref reader, out var ").Append(temp).AppendLine("))");
        sb.Append(p).AppendLine("    return false;");
        sb.Append(p).Append(targetExpr).Append(" = ").Append(temp).AppendLine(";");
        return true;
    }

    private static bool TryGetListElementType(ITypeSymbol type, out ITypeSymbol? elementType)
    {
        elementType = null;
        if (type is not INamedTypeSymbol named || !named.IsGenericType)
            return false;

        if (named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) !=
            "global::System.Collections.Generic.List<T>")
            return false;

        elementType = named.TypeArguments[0];
        return true;
    }

    private static bool ImplementsSerializable(ITypeSymbol type, INamedTypeSymbol serializableSymbol)
    {
        return type is INamedTypeSymbol named
                && named.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, serializableSymbol));
    }

    private static string GetLocalInitializer(ITypeSymbol type)
    {
        return CanAssignNullOnDeserialize(type) ? " = default;" : " = default!;";
    }

    private static bool CanAssignNullOnDeserialize(ITypeSymbol type)
    {
        if (type.IsValueType)
            return type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

        return type.NullableAnnotation != NullableAnnotation.NotAnnotated;
    }

    private static ITypeSymbol RemoveNullable(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            return named.TypeArguments[0];

        return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
    }

    private static string Indent(int level) => new(' ', level * 4);

    private static string BuildJaggedArrayCreationExpression(IArrayTypeSymbol array, string firstLengthExpr)
    {
        var baseType = (ITypeSymbol)array;
        var depth = 0;
        while (baseType is IArrayTypeSymbol nested && nested.Rank == 1)
        {
            depth++;
            baseType = nested.ElementType;
        }

        var baseTypeName = baseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return $"new {baseTypeName}[{firstLengthExpr}]{string.Concat(Enumerable.Repeat("[]", depth - 1))}";
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
    {
        foreach (var type in root.GetTypeMembers())
            foreach (var nested in GetAllTypes(type))
                yield return nested;

        foreach (var ns in root.GetNamespaceMembers())
            foreach (var type in GetAllTypes(ns))
                yield return type;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamedTypeSymbol type)
    {
        yield return type;
        foreach (var nested in type.GetTypeMembers())
            foreach (var child in GetAllTypes(nested))
                yield return child;
    }

    private static bool Implements(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
    {
        return type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol));
    }

    private static bool HasParameterlessConstructor(INamedTypeSymbol type)
    {
        if (type.InstanceConstructors.Length == 0)
            return true;

        return type.InstanceConstructors.Any(ctor => ctor.Parameters.Length == 0 && !ctor.IsStatic);
    }

    private static bool HasAttribute(ISymbol symbol, INamedTypeSymbol? attr)
    {
        if (attr == null)
            return false;

        return symbol.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr)
                                               || SymbolEqualityComparer.Default.Equals(a.AttributeClass?.OriginalDefinition, attr));
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(s => s.Modifiers.Any(m => m.Text == "partial"));
    }

    private static bool HasExplicitSerializationMethods(INamedTypeSymbol type)
    {
        var serialize = type.GetMembers("Serialize").OfType<IMethodSymbol>().Any(m => !m.IsStatic && m.Parameters.Length == 1);
        var deserialize = type.GetMembers("Deserialize").OfType<IMethodSymbol>().Any(m => !m.IsStatic && m.Parameters.Length == 1);
        return serialize && deserialize;
    }

    private static ImmutableArray<IPropertySymbol> GetStateProperties(
        INamedTypeSymbol type,
        INamedTypeSymbol? componentStateAttribute,
        INamedTypeSymbol? componentStateGenericAttribute)
    {
        return type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic)
            .Where(p => p.GetMethod != null && p.SetMethod != null)
            .Where(p => p.GetAttributes().Any(a =>
                SymbolEqualityComparer.Default.Equals(a.AttributeClass, componentStateAttribute)
                || SymbolEqualityComparer.Default.Equals(a.AttributeClass?.OriginalDefinition, componentStateGenericAttribute)))
            .OrderBy(p => p.Name, System.StringComparer.Ordinal)
            .ToImmutableArray();
    }

    private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        var current = type.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }

        return false;
    }

    private static string BuildHintName(INamedTypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   .Replace("global::", string.Empty)
                   .Replace('<', '_')
                   .Replace('>', '_')
                   .Replace('.', '_') + ".BinarySerialization.g.cs";
    }

    private static void AppendContainingTypeDeclarations(StringBuilder builder, INamedTypeSymbol containingType)
    {
        var stack = new Stack<INamedTypeSymbol>();
        var current = containingType;
        while (current != null)
        {
            stack.Push(current);
            current = current.ContainingType;
        }

        var indentLevel = 0;
        while (stack.Count > 0)
        {
            var type = stack.Pop();
            var indent = new string(' ', indentLevel * 4);
            builder.Append(indent).Append("partial ").Append(GetTypeKeyword(type)).Append(' ').Append(type.Name);

            if (type.TypeParameters.Length > 0)
                builder.Append('<').Append(string.Join(", ", type.TypeParameters.Select(tp => tp.Name))).Append('>');

            builder.AppendLine();
            builder.Append(indent).AppendLine("{");
            indentLevel++;
        }
    }

    private static void AppendContainingTypeClosures(StringBuilder builder, INamedTypeSymbol containingType)
    {
        var depth = 0;
        var current = containingType;
        while (current != null)
        {
            depth++;
            current = current.ContainingType;
        }

        for (var i = depth - 1; i >= 0; i--)
            builder.Append(new string(' ', i * 4)).AppendLine("}");
    }

    private static string GetTypeKeyword(INamedTypeSymbol symbol)
    {
        if (symbol.IsRecord)
            return symbol.IsValueType ? "record struct" : "record";

        return symbol.TypeKind switch
        {
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => "class"
        };
    }
}

