<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <Configurations>Debug;Release;ExportDebug;ExportRelease</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'ExportRelease'">
        <Optimize>true</Optimize>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="Directory.Build.*" Visible="false"/>
        <None Include=".gdignore" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\MinionLib.RitsuAdapters\*.cs" LogicalName="EmbeddedSources.RitsuAdapters.%(FileName).cs" Visible="false"/>
        <EmbeddedResource Include="..\MinionLib.BaseLibAdapters\*.cs" LogicalName="EmbeddedSources.BaseLibAdapters.%(FileName).cs" Visible="false"/>
    </ItemGroup>
</Project>