using System;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MinionLib.Generators.Adapters;

internal static class AdapterGeneratorHelper
{
    /// <summary>
    ///     检测特定程序集（DLL）或顶级命名空间是否存在
    /// </summary>
    public static bool CheckPresence(Compilation compilation, string assemblyName, string namespaceName)
    {
        // 1. 检测引用程序集
        var hasDll = compilation.ReferencedAssemblyNames.Any(ai =>
            string.Equals(ai.Name, assemblyName, StringComparison.OrdinalIgnoreCase));

        if (hasDll) return true;

        // 2. 检测顶级命名空间
        var hasNamespace = compilation.GlobalNamespace.GetNamespaceMembers().Any(n =>
            string.Equals(n.Name, namespaceName, StringComparison.OrdinalIgnoreCase));

        return hasNamespace;
    }

    /// <summary>
    ///     提取指定前缀的嵌入源文件并释放到目标项目中
    /// </summary>
    public static void EmitEmbeddedSources(SourceProductionContext spc, string resourcePrefix)
    {
        var assembly = typeof(AdapterGeneratorHelper).Assembly;

        // 筛选出符合特定前缀的资源
        var resourceNames = assembly.GetManifestResourceNames()
            .Where(name => name.StartsWith(resourcePrefix, StringComparison.Ordinal))
            .ToArray();

        foreach (var resourceName in resourceNames)
        {
            using var stream = assembly.GetManifestResourceStream(resourceName);
            if (stream == null) continue;

            using var reader = new StreamReader(stream, Encoding.UTF8);
            var rawSource = reader.ReadToEnd();

            // 提取文件名（例如 "ModComponentsCardTemplate.cs"）
            var fileName = resourceName.Substring(resourcePrefix.Length);

            // 为了防止同名冲突，将前缀名融入到 hintName 中
            // 例如："EmbeddedSources.RitsuAdapters." 转换成 "RitsuAdapters."
            var category = resourcePrefix.Replace("EmbeddedSources.", "");
            var hintName = $"{category}{Path.ChangeExtension(fileName, ".g.cs")}";

            // 拼接自动生成的声明和可空上下文启用
            var finalSource = $$$"""
                                 // <auto-generated/>
                                 // This file was automatically generated by MinionLib.Generators.
                                 // Do not modify this file directly.

                                 #nullable enable

                                 {{{rawSource}}}
                                 """;

            spc.AddSource(hintName, SourceText.From(finalSource, Encoding.UTF8));
        }
    }
}
