// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable

using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
namespace MinionLib.Component.Utils;

public abstract partial class TimingCardComponent
{
    public override Task OnPlayPrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.OnPlay ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task OnPlayPostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.OnPlay ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task OnEnqueuePlayVfxPrefix(Creature? target, ComponentContext componentContext)
    {
        return Timing == Timing.OnEnqueuePlayVfx ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task OnEnqueuePlayVfxPostfix(Creature? target, ComponentContext componentContext)
    {
        return Timing == Timing.OnEnqueuePlayVfx ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task OnTurnEndInHandPrefix(PlayerChoiceContext choiceContext, ComponentContext componentContext)
    {
        return Timing == Timing.OnTurnEndInHand ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task OnTurnEndInHandPostfix(PlayerChoiceContext choiceContext, ComponentContext componentContext)
    {
        return Timing == Timing.OnTurnEndInHand ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeCardPlayedPrefix(CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCardPlayed ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeCardPlayedPostfix(CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCardPlayed ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardPlayedPrefix(PlayerChoiceContext context, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardPlayed ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardPlayedPostfix(PlayerChoiceContext context, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardPlayed ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardPlayedLatePrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardPlayedLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardPlayedLatePostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardPlayedLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPlayerTurnStartPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPlayerTurnStart ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPlayerTurnStartPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPlayerTurnStart ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeTurnEndPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeTurnEnd ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeTurnEndPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeTurnEnd ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterTurnEndPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTurnEnd ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterTurnEndPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTurnEnd ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterActEnteredPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterActEntered ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterActEnteredPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterActEntered ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterAddToDeckPreventedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterAddToDeckPrevented ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterAddToDeckPreventedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterAddToDeckPrevented ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeAttackPrefix(AttackCommand command, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeAttack ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeAttackPostfix(AttackCommand command, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeAttack ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterAttackPrefix(AttackCommand command, ComponentContext componentContext)
    {
        return Timing == Timing.AfterAttack ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterAttackPostfix(AttackCommand command, ComponentContext componentContext)
    {
        return Timing == Timing.AfterAttack ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterBlockClearedPrefix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterBlockCleared ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterBlockClearedPostfix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterBlockCleared ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeBlockGainedPrefix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeBlockGained ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeBlockGainedPostfix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeBlockGained ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterBlockGainedPrefix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterBlockGained ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterBlockGainedPostfix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterBlockGained ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterBlockBrokenPrefix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterBlockBroken ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterBlockBrokenPostfix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterBlockBroken ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardChangedPilesPrefix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardChangedPiles ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardChangedPilesPostfix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardChangedPiles ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardChangedPilesLatePrefix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardChangedPilesLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardChangedPilesLatePostfix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardChangedPilesLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardDiscardedPrefix(PlayerChoiceContext choiceContext, CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardDiscarded ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardDiscardedPostfix(PlayerChoiceContext choiceContext, CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardDiscarded ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardDrawnEarlyPrefix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardDrawnEarly ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardDrawnEarlyPostfix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardDrawnEarly ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardDrawnPrefix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardDrawn ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardDrawnPostfix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardDrawn ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardEnteredCombatPrefix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardEnteredCombat ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardEnteredCombatPostfix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardEnteredCombat ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardGeneratedForCombatPrefix(CardModel card, bool addedByPlayer, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardGeneratedForCombat ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardGeneratedForCombatPostfix(CardModel card, bool addedByPlayer, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardGeneratedForCombat ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardExhaustedPrefix(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardExhausted ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardExhaustedPostfix(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardExhausted ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeCardAutoPlayedPrefix(CardModel card, Creature? target, AutoPlayType type, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCardAutoPlayed ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeCardAutoPlayedPostfix(CardModel card, Creature? target, AutoPlayType type, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCardAutoPlayed ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCardRetainedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardRetained ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCardRetainedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCardRetained ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeCombatStartPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCombatStart ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeCombatStartPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCombatStart ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeCombatStartLatePrefix(ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCombatStartLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeCombatStartLatePostfix(ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCombatStartLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCombatEndPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCombatEnd ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCombatEndPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCombatEnd ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCombatVictoryEarlyPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCombatVictoryEarly ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCombatVictoryEarlyPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCombatVictoryEarly ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCombatVictoryPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCombatVictory ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCombatVictoryPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCombatVictory ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCreatureAddedToCombatPrefix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCreatureAddedToCombat ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCreatureAddedToCombatPostfix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCreatureAddedToCombat ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterCurrentHpChangedPrefix(Creature creature, decimal delta, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCurrentHpChanged ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterCurrentHpChangedPostfix(Creature creature, decimal delta, ComponentContext componentContext)
    {
        return Timing == Timing.AfterCurrentHpChanged ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterDamageGivenPrefix(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDamageGiven ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterDamageGivenPostfix(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDamageGiven ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeDamageReceivedPrefix(PlayerChoiceContext choiceContext, Creature target, decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeDamageReceived ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeDamageReceivedPostfix(PlayerChoiceContext choiceContext, Creature target, decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeDamageReceived ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterDamageReceivedPrefix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDamageReceived ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterDamageReceivedPostfix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDamageReceived ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterDamageReceivedLatePrefix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDamageReceivedLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterDamageReceivedLatePostfix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDamageReceivedLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeDeathPrefix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeDeath ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeDeathPostfix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeDeath ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterDeathPrefix(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDeath ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterDeathPostfix(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDeath ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterDiedToDoomPrefix(PlayerChoiceContext choiceContext, IReadOnlyList<Creature> creatures, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDiedToDoom ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterDiedToDoomPostfix(PlayerChoiceContext choiceContext, IReadOnlyList<Creature> creatures, ComponentContext componentContext)
    {
        return Timing == Timing.AfterDiedToDoom ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterEnergyResetPrefix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterEnergyReset ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterEnergyResetPostfix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterEnergyReset ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterEnergyResetLatePrefix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterEnergyResetLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterEnergyResetLatePostfix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterEnergyResetLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterEnergySpentPrefix(CardModel card, int amount, ComponentContext componentContext)
    {
        return Timing == Timing.AfterEnergySpent ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterEnergySpentPostfix(CardModel card, int amount, ComponentContext componentContext)
    {
        return Timing == Timing.AfterEnergySpent ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeCardRemovedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCardRemoved ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeCardRemovedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeCardRemoved ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeFlushPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeFlush ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeFlushPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeFlush ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeFlushLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeFlushLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeFlushLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeFlushLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterGoldGainedPrefix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterGoldGained ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterGoldGainedPostfix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterGoldGained ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeHandDrawPrefix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeHandDraw ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeHandDrawPostfix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeHandDraw ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeHandDrawLatePrefix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeHandDrawLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeHandDrawLatePostfix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeHandDrawLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterHandEmptiedPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterHandEmptied ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterHandEmptiedPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterHandEmptied ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterItemPurchasedPrefix(Player player, MerchantEntry itemPurchased, int goldSpent, ComponentContext componentContext)
    {
        return Timing == Timing.AfterItemPurchased ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterItemPurchasedPostfix(Player player, MerchantEntry itemPurchased, int goldSpent, ComponentContext componentContext)
    {
        return Timing == Timing.AfterItemPurchased ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterMapGeneratedPrefix(ActMap map, int actIndex, ComponentContext componentContext)
    {
        return Timing == Timing.AfterMapGenerated ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterMapGeneratedPostfix(ActMap map, int actIndex, ComponentContext componentContext)
    {
        return Timing == Timing.AfterMapGenerated ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingBlockAmountPrefix(decimal modifiedAmount, CardModel? cardSource, CardPlay? cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingBlockAmount ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingBlockAmountPostfix(decimal modifiedAmount, CardModel? cardSource, CardPlay? cardPlay, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingBlockAmount ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingCardPlayCountPrefix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingCardPlayCount ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingCardPlayCountPostfix(CardModel card, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingCardPlayCount ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingCardPlayResultPileOrPositionPrefix(CardModel card, PileType pileType, CardPilePosition position, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingCardPlayResultPileOrPosition ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingCardPlayResultPileOrPositionPostfix(CardModel card, PileType pileType, CardPilePosition position, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingCardPlayResultPileOrPosition ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingOrbPassiveTriggerCountPrefix(OrbModel orb, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingOrbPassiveTriggerCount ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingOrbPassiveTriggerCountPostfix(OrbModel orb, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingOrbPassiveTriggerCount ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingCardRewardOptionsPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingCardRewardOptions ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingCardRewardOptionsPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingCardRewardOptions ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingDamageAmountPrefix(CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingDamageAmount ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingDamageAmountPostfix(CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingDamageAmount ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingEnergyGainPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingEnergyGain ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingEnergyGainPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingEnergyGain ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingHandDrawPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingHandDraw ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingHandDrawPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingHandDraw ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPreventingDrawPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterPreventingDraw ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPreventingDrawPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterPreventingDraw ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingHpLostBeforeOstyPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingHpLostBeforeOsty ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingHpLostBeforeOstyPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingHpLostBeforeOsty ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingHpLostAfterOstyPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingHpLostAfterOsty ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingHpLostAfterOstyPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingHpLostAfterOsty ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingPowerAmountReceivedPrefix(PowerModel power, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingPowerAmountReceived ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingPowerAmountReceivedPostfix(PowerModel power, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingPowerAmountReceived ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingPowerAmountGivenPrefix(PowerModel power, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingPowerAmountGiven ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingPowerAmountGivenPostfix(PowerModel power, ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingPowerAmountGiven ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterModifyingRewardsPrefix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingRewards ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterModifyingRewardsPostfix(ComponentContext componentContext)
    {
        return Timing == Timing.AfterModifyingRewards ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeRewardsOfferedPrefix(Player player, IReadOnlyList<Reward> rewards, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeRewardsOffered ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeRewardsOfferedPostfix(Player player, IReadOnlyList<Reward> rewards, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeRewardsOffered ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterOrbChanneledPrefix(PlayerChoiceContext choiceContext, Player player, OrbModel orb, ComponentContext componentContext)
    {
        return Timing == Timing.AfterOrbChanneled ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterOrbChanneledPostfix(PlayerChoiceContext choiceContext, Player player, OrbModel orb, ComponentContext componentContext)
    {
        return Timing == Timing.AfterOrbChanneled ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterOrbEvokedPrefix(PlayerChoiceContext choiceContext, OrbModel orb, IEnumerable<Creature> targets, ComponentContext componentContext)
    {
        return Timing == Timing.AfterOrbEvoked ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterOrbEvokedPostfix(PlayerChoiceContext choiceContext, OrbModel orb, IEnumerable<Creature> targets, ComponentContext componentContext)
    {
        return Timing == Timing.AfterOrbEvoked ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterOstyRevivedPrefix(Creature osty, ComponentContext componentContext)
    {
        return Timing == Timing.AfterOstyRevived ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterOstyRevivedPostfix(Creature osty, ComponentContext componentContext)
    {
        return Timing == Timing.AfterOstyRevived ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforePotionUsedPrefix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Timing == Timing.BeforePotionUsed ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforePotionUsedPostfix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Timing == Timing.BeforePotionUsed ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPotionUsedPrefix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPotionUsed ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPotionUsedPostfix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPotionUsed ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPotionDiscardedPrefix(PotionModel potion, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPotionDiscarded ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPotionDiscardedPostfix(PotionModel potion, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPotionDiscarded ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPotionProcuredPrefix(PotionModel potion, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPotionProcured ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPotionProcuredPostfix(PotionModel potion, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPotionProcured ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforePowerAmountChangedPrefix(PowerModel power, decimal amount, Creature target, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.BeforePowerAmountChanged ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforePowerAmountChangedPostfix(PowerModel power, decimal amount, Creature target, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.BeforePowerAmountChanged ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPowerAmountChangedPrefix(PowerModel power, decimal amount, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPowerAmountChanged ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPowerAmountChangedPostfix(PowerModel power, decimal amount, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPowerAmountChanged ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPreventingBlockClearPrefix(AbstractModel preventer, Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPreventingBlockClear ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPreventingBlockClearPostfix(AbstractModel preventer, Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPreventingBlockClear ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPreventingDeathPrefix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPreventingDeath ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPreventingDeathPostfix(Creature creature, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPreventingDeath ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterRestSiteHealPrefix(Player player, bool isMimicked, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRestSiteHeal ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterRestSiteHealPostfix(Player player, bool isMimicked, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRestSiteHeal ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterRestSiteSmithPrefix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRestSiteSmith ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterRestSiteSmithPostfix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRestSiteSmith ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterRewardTakenPrefix(Player player, Reward reward, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRewardTaken ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterRewardTakenPostfix(Player player, Reward reward, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRewardTaken ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeRoomEnteredPrefix(AbstractRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeRoomEntered ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeRoomEnteredPostfix(AbstractRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeRoomEntered ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterRoomEnteredPrefix(AbstractRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRoomEntered ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterRoomEnteredPostfix(AbstractRoom room, ComponentContext componentContext)
    {
        return Timing == Timing.AfterRoomEntered ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterShufflePrefix(PlayerChoiceContext choiceContext, Player shuffler, ComponentContext componentContext)
    {
        return Timing == Timing.AfterShuffle ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterShufflePostfix(PlayerChoiceContext choiceContext, Player shuffler, ComponentContext componentContext)
    {
        return Timing == Timing.AfterShuffle ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterStarsSpentPrefix(int amount, Player spender, ComponentContext componentContext)
    {
        return Timing == Timing.AfterStarsSpent ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterStarsSpentPostfix(int amount, Player spender, ComponentContext componentContext)
    {
        return Timing == Timing.AfterStarsSpent ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterStarsGainedPrefix(int amount, Player gainer, ComponentContext componentContext)
    {
        return Timing == Timing.AfterStarsGained ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterStarsGainedPostfix(int amount, Player gainer, ComponentContext componentContext)
    {
        return Timing == Timing.AfterStarsGained ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterForgePrefix(decimal amount, Player forger, AbstractModel? source, ComponentContext componentContext)
    {
        return Timing == Timing.AfterForge ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterForgePostfix(decimal amount, Player forger, AbstractModel? source, ComponentContext componentContext)
    {
        return Timing == Timing.AfterForge ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterSummonPrefix(PlayerChoiceContext choiceContext, Player summoner, decimal amount, ComponentContext componentContext)
    {
        return Timing == Timing.AfterSummon ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterSummonPostfix(PlayerChoiceContext choiceContext, Player summoner, decimal amount, ComponentContext componentContext)
    {
        return Timing == Timing.AfterSummon ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterTakingExtraTurnPrefix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTakingExtraTurn ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterTakingExtraTurnPostfix(Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTakingExtraTurn ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterTargetingBlockedVfxPrefix(Creature blocker, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTargetingBlockedVfx ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterTargetingBlockedVfxPostfix(Creature blocker, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTargetingBlockedVfx ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeSideTurnStartPrefix(PlayerChoiceContext choiceContext, CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeSideTurnStart ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeSideTurnStartPostfix(PlayerChoiceContext choiceContext, CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeSideTurnStart ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterSideTurnStartPrefix(CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.AfterSideTurnStart ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterSideTurnStartPostfix(CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Timing == Timing.AfterSideTurnStart ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPlayerTurnStartEarlyPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPlayerTurnStartEarly ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPlayerTurnStartEarlyPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPlayerTurnStartEarly ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterPlayerTurnStartLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPlayerTurnStartLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterPlayerTurnStartLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.AfterPlayerTurnStartLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforePlayPhaseStartPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.BeforePlayPhaseStart ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforePlayPhaseStartPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Timing == Timing.BeforePlayPhaseStart ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeTurnEndVeryEarlyPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeTurnEndVeryEarly ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeTurnEndVeryEarlyPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeTurnEndVeryEarly ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task BeforeTurnEndEarlyPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeTurnEndEarly ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task BeforeTurnEndEarlyPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.BeforeTurnEndEarly ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override Task AfterTurnEndLatePrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTurnEndLate ? OnTimingPrefix() : Task.CompletedTask;
    }
    public override Task AfterTurnEndLatePostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Timing == Timing.AfterTurnEndLate ? OnTimingPostfix() : Task.CompletedTask;
    }
    public override void OnUpgradePrefix(ComponentContext componentContext)
    {
        if (Timing == Timing.OnUpgrade) OnTimingPrefix();
    }
    public override void OnUpgradePostfix(ComponentContext componentContext)
    {
        if (Timing == Timing.OnUpgrade) OnTimingPostfix();
    }
}
